### PR TITLE
generate powerful rewards

### PR DESCRIPTION
**Pull request by delphiactual**
irt https://github.com/DestinyItemManager/DIM/pull/4166

I found these on Milestones I cannot see another way to find `powerful equipment.` except for checking against every itemhash.

### CODE REVIEW

**Comment by sundevour** [comment]
only in this list
```
66825403 //InventoryItem "Legendary Engram"
226330008 //InventoryItem "Prime Engram"
506041342 //InventoryItem "Legendary Engram"
646467119 //InventoryItem "Prime Engram"
782362349 //InventoryItem "Legendary Engram"
914894006 //InventoryItem "Legendary Engram"
1261433463 //InventoryItem "Legendary Engram"
2089363823 //InventoryItem "Legendary Engram"
2769545932 //InventoryItem "Luminous Engram"
3308857600 //InventoryItem "Legendary Engram"
3879752304 //InventoryItem "Legendary Engram"
```

in both
```
1800172820 //InventoryItem "Luminous Vanguard Engram"
2481239683 //InventoryItem "Luminous Vanguard Engram"
2558839803 //InventoryItem "Luminous Planetary Engram"
2566956006 //InventoryItem "Luminous Crucible Engram"
2770239081 //InventoryItem "Luminous Crucible Engram"
3829523414 //InventoryItem "Luminous Planetary Engram"
4039143015 //InventoryItem "Powerful Gear"
4143344829 //InventoryItem "Luminous Engram"
```

only in bhollis' list
```
993006552 //InventoryItem "Luminous Crucible Engram"
1204101093 //InventoryItem "Luminous Vanguard Engram"
2484791497 //InventoryItem "Luminous Planetary Engram"
2646629159 //InventoryItem "Luminous Engram"
4249081773 //InventoryItem "Powerful Armor"
```

**Comment by delphiactual** [comment]
Ahh the ones in bhollis list only are missing itemCategoryHashes

**Comment by delphiactual** [comment]
only in this list
```
66825403 //InventoryItem "Legendary Engram"
226330008 //InventoryItem "Prime Engram"
334865270 //InventoryItem "Legendary Engram"***
506041342 //InventoryItem "Legendary Engram"
646467119 //InventoryItem "Prime Engram"
782362349 //InventoryItem "Legendary Engram"
914894006 //InventoryItem "Legendary Engram"
1261433463 //InventoryItem "Legendary Engram"
2089363823 //InventoryItem "Legendary Engram"
2769545932 //InventoryItem "Luminous Engram"
3308857600 //InventoryItem "Legendary Engram"
3529617614 //InventoryItem "Legendary Engram"***
3879752304 //InventoryItem "Legendary Engram"
```
in both
```
993006552 //InventoryItem "Luminous Crucible Engram"
1204101093 //InventoryItem "Luminous Vanguard Engram"
1800172820 //InventoryItem "Luminous Vanguard Engram"
2481239683 //InventoryItem "Luminous Vanguard Engram"
2484791497 //InventoryItem "Luminous Planetary Engram"
2558839803 //InventoryItem "Luminous Planetary Engram"
2566956006 //InventoryItem "Luminous Crucible Engram"
2646629159 //InventoryItem "Luminous Engram"
2770239081 //InventoryItem "Luminous Crucible Engram"
3829523414 //InventoryItem "Luminous Planetary Engram"
4039143015 //InventoryItem "Powerful Gear"
4143344829 //InventoryItem "Luminous Engram"
```
only in bhollis' list
```
4249081773 //InventoryItem "Powerful Armor"
```

*** denote newly added to just this list

**Comment by delphiactual** [comment]
got the last itemhash that was missing...
bhollis made his list by searching destinysets for `powerful`, so I believe mine is more robustly complete

**Pull request merged**
