### PR TITLE
Generate a mapping from energy type and energy capacity to mod

### PR DESCRIPTION
**Pull request by bhollis**
This makes us a table that allows us to look up the energy capacity mods for Armor 2.0 that are required for each increment of energy capacity, by energy type. For example, to get armor to Arc capacity 3, we'd need all the mods corresponding to `energyMods[DestinyEnergyType.Arc].slice(3)`.

### CODE REVIEW

**Comment by nev-r** [comment]
i assume the slice is wrong or i am misunderstanding, but look like for determining awa costs? very neat

**Review by nev-r — COMMENTED** [review]
i am not sure i see how you are avoiding
https://data.destinysets.com/i/InventoryItem:260714241
in favor of 
https://data.destinysets.com/i/InventoryItem:4197017644

i think it might just be a coincidence because they have lower hash numbers and higher are overwriting?

**Comment by bhollis** [comment]
I think that's probably right, it's by accident. I can fix.

I think the slice is right? I've offset everything by 1 in the array (since there's no mod for zero energy) so since the slice is exclusive, it should get elements [0, 1, 2] which are the mods required to go to energy 1, 2, 3.

**Comment by nev-r** [comment]
ignore the slice comment sorry, it snuck back into the github draft via a refresh or something

**Review by delphiactual — APPROVED** [review]

**Pull request merged**
