### PR TITLE
Generate collectible hashes

### PR DESCRIPTION
**Pull request by delphiactual**
Automate collectible hash finding.
```
Same name, same ichs, and one missing a collectible hash

Possibly only needs to be run on armor.

and then link our specific source search strings to collectible sources
---OR---
Link the missing collectible hash to the InventoryItemHash
```
This could use some optimization from you @sundevour

### CODE REVIEW

**Comment by delphiactual** [comment]
Need to remove `s8-source-info.ts` once `missing-collectible-hashes.json` is incorporated into DIM

**Comment by delphiactual** [comment]
let's actually make `missing-collectible-hashes.json` an intermediate step to generate `missing-source-info.ts`

**Comment by bhollis** [comment]
Does this only generate entries when the collectibleHash is missing?

**Comment by delphiactual** [comment]
yes

**Comment by delphiactual** [comment]
this will replace the hopefully named `s8-missings-sources.ts` with `missing-source-info.ts` as a drop-in replacement that is automatically updated

**Pull request merged**
