### PR TITLE
New Sources +update sources

### PR DESCRIPTION
**Pull request by delphiactual**
Add new sources
Update old sources

`source:shatteredthrone` may end up breaking things as there is no source, just items

### CODE REVIEW

**Comment by delphiactual** [comment]
for some reason `3389857033` is not assigned even though it has the `strike` keyword

**Comment by nev-r** [comment]
sources.json
`  "3389857033": "Earn Crucible Engrams during Season 3 to unlock and equip this ornament.",`

**Comment by nev-r** [comment]
it has an inconsistent source string depending on which item it's pulled from because it's falling back to item description

**Comment by delphiactual** [comment]
added the option to directly add sourceHash to a keyword

**Comment by delphiactual** [comment]
running `yarn generate:missing-collectibles` seems to also run `yarn generate:source-info` again

**Pull request merged**
